# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb0c853f24f1d5e30792a59f47cd8c7d1174bf63113faa45b47049986347d428c433b0bc924157ffb21eddb8dceb708203fdbe341b6b3a64014e9dfeca598f06

test:
  secret_key_base: bf6bb6539ac8a87fb9b0e07ff408c40d25b1d244a3d66083dd3fdf557752ebe4fd29f7333252ed6a622f9c630a6a5da3bfba486d2e1f5262e7570b5fdf94758e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
